---

- name: Add repo key
  apt_key: url=https://artifacts.elastic.co/GPG-KEY-elasticsearch
  become: yes
  when: ansible_os_family == 'Debian'
- name: Add repo source
  apt_repository:
    repo: 'deb https://artifacts.elastic.co/packages/5.x/apt stable main'
    filename: 'elastic-5.x'
    update_cache: yes
  become: yes
  when: ansible_os_family == 'Debian'
