---

- name: Install packages
  apt: name=elasticsearch state=latest
  become: yes
  when: ansible_os_family == 'Debian'
- name: Set jvm options
  template:
    src: jvm.options.j2
    dest: /etc/elasticsearch/jvm.options
    mode: 664
  become: yes
- name: Enable and start service
  service:
    name: elasticsearch
    state: started
    enabled: yes
  become: yes
  when: ansible_os_family == 'Debian'
